import { getFullUserHistory } from "../../../db/getActions"
import { getServerSession } from "next-auth"
import { getUserId } from "../../../db/insertActions"
import { notFound } from "next/navigation"
import { Suspense } from "react"
import Loading from "./loading"
import Header from "@/components/Header"
import HistoryOverview from "@/components/History/HistoryOverview"
import InfoComponent from "@/components/informational/InfoComponent"
import { Results } from "@/interfaces/Phase3"
import P3_ResultsTable from "@/components/Phase3/P3_ResultsTable"
import P3_CompareButton from "@/components/Phase3/P3_CompareButton"
import { Chip } from "@nextui-org/react"

export default async function Home({
  params,
}: {
  params: { historyId: string }
}) {
  const session = await getServerSession()
  const userId = await getUserId({ newEmail: session?.user?.email || "" })

  const history = await getFullUserHistory({
    userId,
    logId: params.historyId,
  })

  if (!history) {
    notFound()
  }

  let tableResults: Results | undefined = undefined

  try {
    tableResults = JSON.parse(history.searchResults ?? "")
  } catch {
    console.error("Error parsing search results")
  }

  return (
    <Suspense fallback={<Loading />}>
      <main className="bg-backgroundLight dark:bg-backgroundDark">
        <Header
          isDashboard={false}
          userMenuShowBoth={true}
          title="Search History"
        >
          <HistoryOverview history={history} />

          {tableResults != undefined ? (
            <div className="mb-9 flex flex-col items-center">
              <P3_ResultsTable incoming_results={tableResults} />
              <P3_CompareButton
                isHistory={true}
                history={history.searchResults || ""}
              />
            </div>
          ) : (
            <Chip color="danger" className="m-5">
              Error loading results
            </Chip>
          )}
        </Header>

        <InfoComponent title="History" icon={2}>
          <>
            <p>The results above show the detailed history of your search.</p>

            <br />

            <p>
              These include the information generated by our system and the ones
              selected by you for this specific search.
            </p>

            <br />

            <p>
              The{" "}
              <Chip variant="dot" color="secondary">
                purple
              </Chip>{" "}
              chips represent those categories created by you.
            </p>

            <br />

            <p>
              Use the action buttons to provide feedback on the generated topics
              or delete the search from your history.
            </p>

            <br />
          </>
        </InfoComponent>
      </main>
    </Suspense>
  )
}
