import { getFullUserHistory } from "../../../../db/getActions"
import { getServerSession } from "next-auth"
import { getUserId } from "../../../../db/insertActions"
import { notFound } from "next/navigation"
import { Suspense } from "react"
import Loading from "./loading"
import Header from "@/app/components/Header"
import HistoryOverview from "@/app/components/History/HistoryOverview"
import InfoComponent from "@/app/components/informational/InfoComponent"
import { Chip } from "@nextui-org/react"

export default async function Home({
  params,
}: {
  params: { historyId: string }
}) {
  const session = await getServerSession()
  const userId = await getUserId({ newEmail: session?.user?.email || "" })

  const history = await getFullUserHistory({
    userId,
    logId: params.historyId,
  })

  if (!history) {
    notFound()
  }

  return (
    <Suspense fallback={<Loading />}>
      <main className="bg-backgroundLight dark:bg-backgroundDark">
        <Header
          isDashboard={false}
          userMenuShowBoth={true}
          title="Search History"
        >
          <HistoryOverview history={history} />
        </Header>

        <InfoComponent title="History" icon={2}>
          <>
            <p>The results above show the detailed history of your search.</p>

            <br />

            <p>
              These include the information generated by our system and the ones
              selected by you for this specific search.
            </p>

            <br />

            <p>
              The{" "}
              <Chip variant="dot" color="secondary">
                purple
              </Chip>{" "}
              chips represent those categories created by you.
            </p>

            <br />

            <p>
              Use the action buttons to provide feedback on the generated topics
              or delete the search from your history.
            </p>

            <br />
          </>
        </InfoComponent>
      </main>
    </Suspense>
  )
}
