from .config import (
    OPENAI_MODEL_NAME, 
    CHUNK_OVERLAP, 
    CHUNK_SIZE, 
    NUM_GEN_LINKS, 
    INDEX_K,
    MAX_TOKENS,
    TEMPERATURE,
    SCRAPE_TIMEOUT,
    LINK_SEARCH_PROVIDER,
    PROHIBITED_LINKS)