OPENAI_MODEL_NAME = "gpt-4-1106-preview"
MAX_TOKENS = 1500
TEMPERATURE = 0.0

CHUNK_SIZE = 400
CHUNK_OVERLAP = 50
INDEX_K = 10

NUM_GEN_LINKS = 10
NUM_NEWS_LINKS = 3
SCRAPE_TIMEOUT = 5

SPREADSHEET_NAME = "Generative AI Tools Table"
WORKSHEET = 0
MAIN_COLUMN = "Tool Name"
